name: Auto-Merge Release PR

on:
  workflow_run:
    workflows: ['Lint and build']
    types:
      - completed

permissions:
  pull-requests: write

jobs:
  merge_release_pr:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'develop' && github.actor == 'github-actions[bot]' && github.event_name == 'pull_request' }}
    permissions:
      pull-requests: write
      contents: write
    steps:
      - run: |
          gh pr review --approve "$PR_URL"
          gh pr merge --rebase --auto "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
