name: Lint and build

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-lint:
    uses: GEWIS/actions/.github/workflows/lint-and-build-yarn.yml@v1
    with:
      node-version: '22.x'
      lint: true
      format: true
      build: true
  test:
    needs: [build-and-lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start Planka
        run: docker compose -f "docker-compose.yml" up -d --build
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: corepack enable
      - run: yarn
      - run: yarn test
      - name: Stop Planka
        if: always()
        run: docker compose -f "docker-compose.yml" down
  dependabot:
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' }}
    steps:
      - id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
      - run: |
          gh pr review --approve "$PR_URL"
          gh pr merge --squash --auto "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
