name: Semantic Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  versioning:
    uses: GEWIS/actions/.github/workflows/versioning.yml@v1

  publish-npm:
    uses: GEWIS/actions/.github/workflows/npm-release.yml@v1
    needs: versioning
    if: ${{ needs.versioning.outputs.next_version != '' }}
    with:
      node-version: '22.x'
      version: ${{ needs.versioning.outputs.next_version }}
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}