name: Scheduled semantic release

on:
  schedule:
    - cron: '0 0 * * 5'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  create_release_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create Pull Request
        run: |
          PR_NUMBER=$(gh pr list --head develop --base main --state open --author 'github-actions[bot]' --json number --jq '.[0].number')

          if [ -n "$PR_NUMBER" ]; then
            echo "Existing release pull request found (#$PR_NUMBER), skipping creation."
            echo "pr_url=https://github.com/${GITHUB_REPOSITORY}/pull/$PR_NUMBER" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "No existing release pull request found, creating a new one."
          PR_URL=$(gh pr create \
            --base main \
            --head develop \
            --title "chore(release): merge develop into main" \
            --body "Automated scheduled release PR")
          echo "pr_url=$PR_URL" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
